name: maintenance_system
description: Aplikasi Ticketing IT & Fasilitas Rumah Sakit
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Supabase - backend utama
  supabase_flutter: ^2.3.4

  # State management
  flutter_riverpod: ^2.5.1

  # Navigasi
  go_router: ^13.2.0

  # Upload foto
  image_picker: ^1.1.2

  # Tampilkan gambar dari URL
  cached_network_image: ^3.3.1

  # Format tanggal
  intl: ^0.19.0

  # Loading indicator
  shimmer: ^3.0.0

  # Toast / snackbar
  fluttertoast: ^8.2.4

  # Icon tambahan
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
